### ISSUE TITLE
0.12.2 can't access shared memory from another process on Windows

### ISSUE THREAD

**Issue by bin-cat** [elast0ny/mem_file#82]
Trying to open shared memory of third-party application that is created only as named object.
```
ShmemConf::new().os_id("TestNamedObject").open()
```
fails with OS error 2 (No such file or directory) because open_mapping tries to access non-existent %TEMP%\shared-memory-rs\TestNamedObject.
It worked correctly in 0.11.

**Comment by elast0ny** [comment]
Thanks for submitting this issue. Like you said, this behaviour was introduced in 12.X on Windows in order to mimic how shared memory works on posix systems.

I agree that the crate should be able to handle shared memory mappings from external processes tho so a fix will have to be implemented to address this issue

**Comment by elast0ny** [comment]
This should now work on 0.12.3
